*** Construction d'un dictionnaire français pour Plover
La base de données lexicales libre [[http://www.lexique.org/][Lexique]] est le fondement de la
construction d'un dictionnaire sténotypique au format JSON requis par
le projet [[http://plover.stenoknight.com/][Plover]].

Le fichier original contenant cette base de données est
~Lexique380.txt~.

Les colonnes qui nous intéressent dans cette large base, qui se
présente sous forme d'un tableau texte géant, sont ~1_ortho~ et
~23_syll~.

J'ai dû m'y reprendre à plusieurs reprises sur une période de
plusieurs mois pour aboutir au fichier ~dict-base.txt~.[fn:1]

Le fichier ~dict-base-uniq.txt~ est une version expurgée de doublons.

Le fichier ~france_french_words.txt~ servant à la vérification
orthographique[fn:2] provient également de la base [[http://www.lexique.org/listes/liste_mots.txt][Lexique]].

Le fichier ~fr.aff~ fait partie de la distribution [[http://hunspell.sourceforge.net/][Hunspell]], un
analyseur orthographique et morphologique prenant en charge la langue
française. Il sert de base à la définition des règles d'affixation
contenus dans ~orthography.py~.

*** À propos de la sténotypie
La sténotypie est une méthode d'écriture et tend à représenter le
parole dans une langue donnée par les sons que celle-ci est en mesure
de produire.

Elle tire en cela son héritage de la sténographie en lui apportant une
importante amélioration : tracés à la main, les caractères
sténographiques sont propres au sténographe qui les a dessinés et
peuvent difficilement être interprétés par un autre lecteur.

La sténotype - ainsi est appelée la machine de sténotypie - apporte
donc le moyen de produire des signes sténographiques "types"
reconnaissables par n'importe quel lecture instruit des règles de
base.

Le clavier de la sténotype Grandjean en usage en France a été conçu
par l'ingénieur [[http://fr.wikipedia.org/wiki/Marc_Grandjean][Marc Grandjean]] (1882-1949).

#+BEGIN_EXAMPLE
  ___                                           ___
 | S |___                                   ___| D |
 |___| P |___                           ___| ᴎ |___|
 | K |___| T |___                   ___| I |___| C |
 |___| M |___| * |___     _     ___| A |___| $ |___|
     |___| F |___| N |   / \   | O |___| Ł |___|
         |___| R |___|  /   \  |___| U |___|
             |___| L | /  Y  \ | E |___|
                 |___||       ||___|
                       \_____/
#+END_EXAMPLE

Les cinq doigts de chaque main se positionnement d'un côté et de
l'autre de la touche centrale ~Y~, sur la rangée du bas. C'est ce
qu'on appelle la ~position de départ~ et de repos.

La touche du milieu ~Y~ n'est actionnée que par le pouce de la main
gauche qui reviendra immédiatement après sur sa touche de repos,
c'est-à-dire le ~L~.

Une prise sténotypique consiste à appuyer sur plusieurs touches à la
fois et produit un accord représentant une unité de son.


- La partie gauche du clavier, actionnée par les doigts de la main
  gauche, représente les ~sons de initiaux~ et est constituée de
  consonnes seulement ;
- Les voyelles (~OEAUI~) sont placées sur la partie droite du clavier,
  actionnée par les doigts de la main droite ;
- Les signes parfois étranges (~Łᴎ$DC~) à l'extrême droite
  représentent les ~sons finaux~.

Un exemple pour bien comprendre :

- Affaire s'écrira A/FEŁ
- Rapide  s'écrira RA/PID

Une explication. Pour écrire A/FEŁ :

1) On appuie avec l'index de la main droite sur ~A~
2) On relâche puis on fait revenir son index à sa position de départ
   c'est-à-dire au dessus de la touche ~U~.

3) On appuie de son majeur de la main gauche sur la touche ~F~ ;
4) Tout en maintenant ~F~ appuyé, vous appuyez du pouce de la main
   droite sur la touche ~E~
5) De son majeur droit, on enfonce la touche ~Ł~.
6) Les trois touches sont toutes appuyées comme pour un accord de
   piano.
7) On relâche les touches toutes à la fois
8) On fait revenir ses doigts à leurs positions de repos, sur la rangée
   du bas. Il se trouve que pour cette exemple ils y sont déjà.

Ce n'est pas le cas dans notre deuxième exemple, le mot ~RA/PID~ :

1) Index gauche sur la touche ~R~
2) Index droit sur ~A~
3) On relâche les deux doigts et on ramène l'index droit à se position
   de départ au dessus de ~U~.
4) Le signe ~/~ indique la fin d'un accord.

Le deuxième accord ~PID~ vous l'auriez compris se joue avec :

5) L'annulaire de la main gauche sur ~P~
6) Le majeur de la main droite sur ~I~
7) L'auriculaire droit sur ~D~
8) On relâche l'accord
9) On fait revenir tout ce petit monde à sa place, respectivement ~M~,
   ~Ł~ et ~C~.

Il est important de veillez respecter ce mouvement de va et vient vers
la position de départ après chaque frappe.

Il s'agit d'une stratégie d'apprentissage, l'objectif étant de créer
des réactions réflexes sur le modèle d'un coureur au 100 mètres :
celui-ci doit s'entraîner à réduire son temps de réaction entre le top
de départ et sa première impulsion musculaire de propulsion.

Pour un sténotypiste ce temps de réaction est aussi important et pour
ce faire il faut, comme pour un coureur au 100 mètres, se tenir sur
des starting-blocks matérialisés par la station de départ, les 10
doigts placés sur la première rangée.

*** À propos du dictionnaire français pour Plover
Représenter une langue par ses sons permet aux sténotypistes
professionnels d'atteindre des vitesses de prises dépassant les 230
mots par minute. Cette caractéristique a, toutefois, son revers. Les
~homophones~  :

- vos = veau
- eau = aux
- ce = se
- à faire = affaire
- abreuver = abreuvés = abreuvez
- ...


Aux homophones s'ajoutent les caractéristiques de la disposition
du clavier français :

- Ville  = F*IŁ
- Vire   = F*IŁ
- Vile   = F*IŁ

- bref   = P*RE$
- braise = P*RE$
- ...

Plusieurs mots s'écrivent en utilisant les mêmes accords. Une des
raisons est que le concepteur de la disposition du clavier, Marc
Grandjean, a choisi d'assigner à certaines touches plusieurs valeurs
potentielles afin que la composition de tous les sons soit possible sur
21 touches. Ainsi :

- Ł peut désigner les sons "L" ou "R"
- $ peut désigner les sons "S", "Z", "F" ou "V"
- D peut désigner les sons "T", "D", "P" ou "B"
- C peut désigner les sons "K" ou "G"

En dépit de tout cela, le lecteur peut déduire la correspondance
correcte, souvent par un mécanisme inconscient de mise en contexte.

Cette opération mentale, plus complexe qu'il n'y paraît, n'est pas
implémentée dans Plover et l'est d'une manière dont l'efficacité est
toute relative dans les logiciels propriétaires payants de
sténotypie assistée par ordinateur.

Le champs d'études le plus en lien avec ce type de problématiques est
le Traitement automatique du langage naturel (TalN).[fn:3]

*** Les limites de l'approche phonétique
En appliquant une approche purement phonétique pour la construction
d'un dictionnaire sténotypique, on est confronté à la réalité suivante :

Sur les quelques *125 700* entrées du dictionnaire de base, *92 000*
mots souffrent d'homophonie, qui représentent *31 000* entrées du
dictionnaire sténotypique.

Un exemple parmi beaucoup d'autres :

#+BEGIN_EXAMPLE
A-LE 	 halez
A-LE 	 hâlés
A-LE 	 halés
A-LE 	 haler
A-LE 	 hâlées
A-LE 	 hâlée
A-LE 	 halée
A-LE 	 hâlé
A-LE 	 halé
A-LE 	 hâlait
A-LE 	 halait
A-LE 	 halaient
A-LE 	 allez
A-LE 	 allés
A-LE 	 allers
A-LE 	 aller
A-LE 	 allées
A-LE 	 allée
A-LE 	 allé
A-LE 	 allait
A-LE 	 allais
A-LE 	 allaient
A-LE 	 allai
#+END_EXAMPLE
23 mots du dictionnaire se transcrivent phonétiquement de la même
manière, avec un seul sténogramme, c'est le cas le plus extrême.

Résoudre cette problématique s'avère donc un préalable incontournable
afin de parvenir à un usage raisonnablement fiable de la sténotypie
avec Plover.

Les écoles américaines de sténotypie tendent à introduire une part
d'orthographe plus ou moins importante dans leurs méthodes.

Ce procédé amène des inconvénients : ajouts de frappes ; dérives vers
des compositions qui n'ont plus aucun trait à la phonétique ;
divergences et cloisonnement des écoles et des méthodes... Rien qui ne
va vers une standardisation de la transcription sténographique.

La contrepartie de cette option aux yeux des sténographes participants
au [[https://groups.google.com/forum/#!forum/ploversteno][groupe de discussion Plover]]

Voici donc le parti pris pour la construction du dictionnaire français :

- La méthode phonétique de base est le socle du dictionnaire.
- La distinction entre les homophones se fait par le biais de frappes
  supplémentaires suivant une convention détaillée au titre suivant.

*** Les ajouts par rapport à la méthode traditionnelle
- Le H muet en début de mot prend une étoile. Ainsi :
  - *An-TRE pour HANTERAIT, qui nous permettra de le distinguer de An-TRE pour ENTRER
- La terminaison des verbes est marquée. Ainsi :
| Phonétique  | orthographe | Ortho-phonétique | Ortho-ergonomico-phonétique |
|-------------+-------------+------------------+-----------------------------|
| TROU-P*L    | trouble     | TROU-P*L         | TROU-P*L                    |
| TROU-P*L    | troubles    | TROU-P*L-$       | TROU-P*L$C                  |
| TROU-P*L    | troublent   | TROU-P*L-EᴎD     | TROU-P*LEᴎD                 |
|-------------+-------------+------------------+-----------------------------|
| TROU-P*LAn  | troublant   | TROU-P*LAᴎ       | TROU-P*LAᴎ                  |
| TROU-P*LAn  | troublants  | TROU-P*LAᴎ-$     | TROU-P*LAᴎ$C                |
| TROU-P*LAnD | troublante  | TROU-P*LAᴎD      | TROU-P*LAᴎD                 |
| TROU-P*LAnD | troublantes | TROU-P*LAᴎD-$    | TROU-P*LAᴎD-$C              |
|-------------+-------------+------------------+-----------------------------|
| TROU-P*LE   | troubler    | TROU-P*LE        | TROU-P*LE                   |
| TROU-P*LE   | troublez    | TROU-P*LE-$      | TROU-P*LE$C                 |
| TROU-P*LE   | troublé     | TROU-P*LE-E      | TROU-P*LE-E                 |
| TROU-P*LE   | troublés    | TROU-P*LE-E$     | TROU-P*LE-E$C               |
| TROU-P*LE   | troublée    | TROU-P*LE-EU     | TROU-P*LEU                  |
| TROU-P*LE   | troublées   | TROU-P*LE-EU$    | TROU-P*LEU$C                |
| TROU-P*LE   | troublais   | TROU-P*LE-AI$    | TROU-P*LEŁ$C                |
| TROU-P*LE   | troublait   | TROU-P*LE-AID    | TROU-P*LEIᴎD                |
| TROU-P*LE   | troublaient | TROU-P*LE-EᴎD    | TROU-P*LE-EᴎD               |
| TROU-P*LE   | troublai    | TROU-P*LE-*      | TROU-P*LE                   |
|-------------+-------------+------------------+-----------------------------|
| TROU-P*LA   | troubla     | TROU-P*LA        | TROU-P*LA                   |
| TROU-P*LA   | troublât    | TROU-P*LA-*      | TROU-P*LA                   |
|-------------+-------------+------------------+-----------------------------|
| TROU-P*L-RE | troublerais | TROU-P*L-RE-AI$  | TROU-P*L-RE                 |
| TROU-P*L-RE | troublerait | TROU-P*L-RE-AID  | TROU-P*L-RE                 |
#+TBLFM: "$4"="$1"
*** La disposition des touches sur le clavier d'ordinateur
La disposition
**** AZERTY
#+BEGIN_EXAMPLE
 ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ _____
|A  |Z  |E  |R  |T  |Y  |U  |I  |O  |P  |^  |$  |Enter|
|___|___|___|___|___|___|___|___|___|___|___|___|     |
 |Q  |S  |D  |F  |G  |H  |J  |K  |L  |M  |Ù  |*  |  ⏎ |
_|___|___|___|___|___|___|___|___|___|___|___|___|____|
   |W  |X  |C  |V  |B  |N  |,  |;  |:  |!  |⇧         |
___|___|___|___|___|___|___|___|___|___|___|__________|
#+END_EXAMPLE
**** Clavier sténotypique anglosaxon en usage dans Plover
#+BEGIN_EXAMPLE
 ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ _____
|S  |T  |P  |H  |*  |*  |F  |P  |L  |T  |D  |   |     |
|__a|__z|__e|__r|__t|__y|__u|__i|__o|__p|__^|___|     |
 |S  |K  |W  |R  |*  |*  |R  |B  |G  |S  |Z  |   |    |
_|__q|__s|__d|__f|__g|__h|__j|__k|__l|__m|__ù|___|____|
   |   |   |A  |O  |   |E  |U  |   |   |   |          |
___|___|___|__c|__v|___|__n|__,|___|___|___|__________|
#+END_EXAMPLE
**** Disposition Grandjean sur un clavier d'ordinateur possibilité n°1
#+BEGIN_EXAMPLE
 ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ _____
|S  |P  |T  |*  |N  |O  |A  |I  |ᴎ  |D  |Z  |   |     |
|__a|__z|__e|__r|__t|__y|__u|__i|__o|__p|__^|___|     |
 |K  |M  |F  |R  |L  |E  |U  |Ł  |$  |C  |Q  |   |    |
_|__q|__s|__d|__f|__g|__h|__j|__k|__l|__m|__ù|___|____|
   |   |   |   |L  |Y  |E  |   |   |   |   |          |
___|___|___|___|__v|__b|__n|___|___|___|___|__________|
#+END_EXAMPLE
**** Disposition Grandjean sur un clavier d'ordinateur possibilité n°2
#+BEGIN_EXAMPLE
 ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ _____
|S  |P  |T  |*  |N  |   |O  |A  |I  |ᴎ  |D  |   |     |
|__a|__z|__e|__r|__t|___|__u|__i|__o|__p|__^|___|     |
 |K  |M  |F  |R  |L  |   |E  |U  |Ł  |$  |C  |   |    |
_|__q|__s|__d|__f|__g|___|__j|__k|__l|__m|__ù|___|
   |   |   |   |L  |Y  |E  |   |   |   |   |          |
___|___|___|___|__v|__b|__n|___|___|___|___|__________|
#+END_EXAMPLE

* Renvois
[fn:1] Le fichier est une correspondance orthographe<-->sténogramme
selon la disposition de clavier sténotypique français. Se rapporter à
[[https://github.com/azizyemloul/plover-france][Plover-france]] pour plus d'informations.

[fn:2] https://groups.google.com/forum/#!topic/ploversteno/pO6WVs9MzK8

[fn:3] Ceci est une piste de travail que je souhaiterai éprouver
notamment dans le cadre de ce projet Plover mais dont la technicité
requière une implication exceptionnelle.

#  LocalWords:  Plover sténotypique texte JSON LocalWords Grandjean
#  LocalWords:  Hunspell orthography.py
