#+BEGIN_EXAMPLE
                  ___                                           ___
                 | S |___                                   ___| D |
                 |___| P |___                           ___| ᴎ |___|
                 | K |___| T |___                   ___| I |___| C |
                 |___| M |___| * |___     _     ___| A |___| $ |___|
                     |___| F |___| N |   / \   | O |___| £ |___|
                         |___| R |___|  /   \  |___| U |___|
                             |___| L | /  Y  \ | E |___|
                                 |___||       ||___|
                                       \_____/

               ___________________________________________________________
              |TAB  |  S|  P|  T|  *|  N|   |  O|  A|  I|  ᴎ|  D|   |Enter|
              |_____|___|___|___|___|___|___|___|___|___|___|___|___|     |
              |MAJ   | K | M | F | R | L | Y | E | U | £ | $ | C |   |  ⏎ |
              |______|___|___|___|___|___|___|___|___|___|___|___|___|____|
              | ⇧  |   |   |   |   |  L|  Y|Y  |E  |   |   |   |⇧         |
              |____|___|___|___|___|___|___|___|___|___|___|___|__________|
#+END_EXAMPLE

*** Si vous voulez essayer Plover avec ce clavier :
Sous Windows, téléchargez le contenu de ce dépôt et lancez
plover.exe, après avoir dézippé l'archive.

Il est très probable que vous receviez un message d'alerte au
démarrage que vous pouvez ignorer.

Appuyez sur ~configure~, puis sur l'onglet ~dictionary~ et, après
avoir supprimé le dictionnaire anglais par défaut, ajoutez les
dictionnaires français en respectant l'ordre numérique.

L'ordre des fichiers a sa raison : Plover renvoie la dernière
traduction du sténogramme après avoir passé tous ces
fichiers dans l'ordre.

Utilisez le fichier ~07_French_User.json~ pour ajouter vos entrées
personnelles. Celles-ci annuleront toutes les autres
entrées sur les autres dictionnaires.

Le dictionnaire est au format JSON. Ce format désigne un fichier texte
dont le tout premier caractère est une accolade ouvrante ~{~.

Chaque ligne de ce fichier contient une "instruction" de la forme
suivante :
#+BEGIN_SRC json
"STE/NO/K*RAnC": "sténogramme",
#+END_SRC
La dernière entrée du dictionnaire ne doit pas finir avec une virgule
mais avec une accolade fermante. Comme ceci :
#+BEGIN_SRC json
"T*El/NYE/MO":"dernier mot"}
#+END_SRC
**** Observation importante :
Les caractères ~£~ (L orné) et ~ᴎ~ (N inversé) sont remplacés dans les
fichiers JSON respectivement par les caractère ~l~ (L minuscule) et
~n~ (N minscule) en raison de l'exotisme des premiers. L'introduction
de l'encodage UTF8 étant récent dans Plover, il vallait mieux opter
pour des caractères plus communs.
*** Construction d'un dictionnaire français pour Plover
La base de données lexicales libre [[http://www.lexique.org/][Lexique]] est le fondement de la
construction d'un dictionnaire sténotypique au format JSON requis par
le projet [[http://plover.stenoknight.com/][Plover]].

Le fichier original contenant cette base de données est
~Lexique380.txt~.

Le fichier ~Atelier/Plover-files/france_french_words.txt~ sert à la
vérification orthographique et provient également des travaux des équipes
[[http://www.lexique.org/listes/liste_mots.txt][Lexique]].

Le fichier ~Hunspell-aff/fr.aff~ fait partie de la distribution
[[http://hunspell.sourceforge.net/][Hunspell]], un analyseur orthographique et morphologique prenant en
charge la langue française. Il sert de base d'inspiration à la
définition des règles d'affixation que dois contenir ~orthography.py~.
*** À propos de la sténotypie
La sténotypie est une méthode d'écriture rapide de la parole.

Elle tire son héritage de la sténographie en lui apportant une
importante amélioration : tracés à la main, les caractères
sténographiques sont propres au sténographe qui les a dessinés et
peuvent difficilement être interprétés par un autre lecteur.

La sténotype - ainsi est appelée la machine de sténotypie - produit
des signes sténographiques "types" reconnaissables par n'importe quel
lecteur instruit des règles de base.

Le clavier de la sténotype Grandjean en usage en France a été conçu
par l'ingénieur [[http://fr.wikipedia.org/wiki/Marc_Grandjean][Marc Grandjean]]. La première sténotype Grandjean a été
commercialisée en 1923.

#+BEGIN_EXAMPLE
 ______                                                                       ______
|      |______                                                         ______|      |
|  S   |      |______                                           ______|      |   D  |
|______|  P   |      |______                             ______|      |   ᴎ  |______|
|      |______|  T   |      |______               ______|      |   I  |______|      |
|  K   |      |______|  *   |      |     ---     |      |   A  |______|      |   C  |
|______|  M   |      |______|  N   |    /   \    |   O  |______|      |   $  |______|
       |______|  F   |      |______|   /     \   |______|      |   £  |______|
	      |______|  R   |      |  /       \  |      |   U  |______|
		     |______|  L   | /    Y    \ |   E  |______|
			    |______||           ||______|
                                     \_________/
#+END_EXAMPLE

Les cinq doigts de chaque main se positionnement d'un côté et de
l'autre de la touche centrale ~Y~, sur la rangée du bas. C'est ce
qu'on appelle la ~position de départ~ ou de repos.

La touche du milieu ~Y~ n'est actionnée que par le pouce de la main
gauche qui reviendra immédiatement sur sa touche de repos,
c'est-à-dire le ~L~.

Une prise sténotypique consiste à appuyer sur plusieurs touches à la
fois et produit un accord représentant une unité de son.


- La partie gauche du clavier, actionnée par les doigts de la main
  gauche, représente les ~sons de initiaux~ et est constituée de
  consonnes seulement ;
- Les voyelles (~OEAUI~) sont placées sur la partie droite du clavier,
  actionnée par les doigts de la main droite ;
- Les signes parfois étranges (~£ᴎ$DC~) à l'extrême droite
  représentent les ~sons finaux~.

Un exemple pour bien comprendre :

- Affaire s'écrira A/FE£
- Rapide  s'écrira RA/PID

Une explication pour écrire A/FE£ :

1) On appuie avec l'index de la main droite sur ~A~
2) On relâche et on fait revenir son index à sa position de départ, au
   dessus de la touche ~U~.

Ceci pour la premier accord qui n'aura au final été constitué que
d'une seule touche. Continuons sur le deuxième accord ~FE£~ qui
compose ce mot :


3) On appuie de son majeur de la main gauche sur la touche ~F~ ;
4) Tout en maintenant ~F~ appuyé, on enfonce du pouce de la main
   droite la touche ~E~
5) Avec le majeur de la main droite, on enfonce la touche ~£~.
6) Les trois touches sont toutes appuyées comme pour un accord de
   piano.
7) On relâche les touches toutes à la fois
8) On fait revenir ses doigts à leurs positions de repos, sur la
   rangée du bas. Il se trouve que pour cette exemple ils y sont déjà.

Ce n'est pas le cas dans le deuxième exemple, le mot ~RA/PID~ :

1) Index gauche sur la touche ~R~
2) Index droit sur ~A~
3) On relâche les deux doigts et on ramène l'index droit à se position
   de départ au dessus de ~U~.
4) Le signe ~/~ indique la fin d'un accord.

Le deuxième accord ~PID~ vous l'aurez compris se joue avec :

5) L'annulaire de la main gauche sur ~P~
6) Le majeur de la main droite sur ~I~
7) L'auriculaire droit sur ~D~
8) On relâche l'accord
9) On fait revenir tout ce petit monde à sa place, respectivement ~M~,
   ~£~ et ~C~.

Il est important de veillez respecter ce mouvement de va et vient
depuis et vers la position de départ après chaque frappe.

Il s'agit d'une stratégie d'apprentissage, l'objectif étant de créer
des réflexes sur le modèle d'un coureur aux 100 mètres : ce sportif
doit s'entraîner à réduire son temps de réaction entre le top de
départ et sa première impulsion musculaire.

Pour un sténotypiste ce temps de réaction est aussi important et pour
ce faire il faut, comme pour un coureur aux 100 mètres, se tenir sur
ses starting-blocks, matérialisés par la position de départ, les 10
doigts placés sur la première rangée.

On a composé deux mots, de 7 et 6 lettres respectivement, avec 2
accords pour chacun, c'est-à-dire 2 mouvements. C'est cette économie
de frappe qui explique la rapidité qu'acquièrent les sténotypistes
professionnels.
**** Les sons du clavier
***** Les sons initiaux
Toutes les consonnes sont représentées à la main gauche.

Certaines sont immédiatement représentées, comme pour les sons Seu,
Peu, Teu, Neu, Keu, Meu, Feu, Reu, Leu.

Il faut comprendre que les caractères représentés sur le clavier ne
désignent pas plus la lettre dans son acception alphabétique que le
son qu'elle produit.

Ainsi, le son Keu correspondant à la touche K servira aussi bien pour
représenter les mots quiétude, que cabaret ou bien karaté. (~KYE/TUD~
~KA/P*A/RE~ ~KA/RA/TE~)

Les sons non-représentés par leurs équivalents orthographiques sont
obtenus par l'adjonction de l'étoile. Ainsi :

- le son Zeu s'obtient par les touches ~S*~
- le son Beu s'obtient par les touches ~P*~
- le son Deu s'obtient par les touches ~T*~
- le son Gueu s'obtient par les touches ~K*~
- le son Veu s'obtient par les touches ~F*~

Dernier élément de cette liste, le son Cheu s'obtient avec les touches
~SK~ pressées ensemble.

#+BEGIN_EXAMPLE
           ______ ______ ______ ______ ______
          |      |      |      |      |      |
          |  S   |  P   |  T   |  *   |  N   |
          |__/\__|______|______|______|______|
          |  \/  |      |      |      |      |
          |  K   |  M   |  F   |  R   |  L   |
          |______|______|______|______|______|

#+END_EXAMPLE

***** Quelques éléments sur le doigté

Pour actionner deux touches qui se trouvent sur la même colonne, il
faut appuyer entre les deux touches, ainsi les deux seront actionnées.

L'exception à cette règle de doigté concerne les pouces.

En théorie, les pouces ne vont jamais sur les rangées du haut (les
touches ~N~ pour la main gauche et ~O~ pour la main droite).

Pour réaliser les accords ~NL~, ~RN~, ~OE~ et ~OU~ on fait ce qu'on
appelle un croisement :

- Pour réaliser le son ~RN~ l'index gauche grimpe d'une rangée, se
  décale vers la droite pour appuyer sur la touche ~N~, pendant que le
  pouce glisse vers la gauche pour appuyer sur la touche ~R~

- Pour réaliser le son ~OU~ l'index droit grimpe d'une rangée, se
  décale vers la gauche pour appuyer sur la touche ~O~. Le pouce
  glisse vers la droite (intérieur de la main) pour appuyer sur la
  touche ~U~

***** Les voyelles (à compléter)
La touche ~E~ désigne le son É (e accent aigu) correspondant au sons
produits par la conjonction "et" et l'auxiliaire être conjugué à la
première personne du singulier au présent de l'indicatif "est".

Pour obtenir le son "e" il faudra appuyer sur les deux touches
~EU~. On ne tapera donc pas ~LE~ pour l'article défini singulier dans
"*le* fourneau" mais seulement la touche ~L~ ce qui donnera
~L/FOU£/NO~. Les touches ~LE~ pressées ensemble désigneront
l'article pluriel dans "*les* biscuits".

Les autres voyelles prises séparément conservent leur valeurs
absolues. Il faut se rappeler, toutefois, que la sténotypie transcrit
le son. Ainsi :

- Le son O dans des mots comme eau, haut, pot, saut, s'écrira quelque soit
  sa graphie avec la même touche ~O~.

- le son OE (diphtongue, ouvert et fermé) comme dans noël, poète... s'obtient par les touches ~OE~
- le son OI comme dans quoi, poids... s'obtient par les touches ~OI~
- le son OU comme dans sous, coup... s'obtient par les touches ~OU~
- le son ON comme dans bonbon, bougeons... s'obtient par les touches ~Oᴎ~
- le son OIN comme dans soin, point... s'obtient par les touches ~OIᴎ~


- le son AU (diphtongue) comme dans bahut, ahurissant... s'obtient par les touches ~AU~
- le son AÏ comme dans ail, taille, gouvernail... s'obtient par les touches ~AI~
- le son AN comme dans argent, enfant... s'obtient par les touches ~Aᴎ~

- le son EU comme dans peur, neuneu... s'obtient par les touches ~EU~
- le son ÉA comme dans réalisateur, béatitude... s'obtient par les touches ~EA~
- le son ÉI comme dans réveil, émerveille... s'obtient par les touches ~EI~
- le son EUIL comme dans écureuil, oeil... s'obtient par les touches ~EU~

- le son I comme dans sténotypie, manie... s'obtient par les touches ~I~
- le son IN comme dans intégral, pingre... s'obtient par les touches ~In~

*Attention :*

- le son ILLE comme dans quille, fille, aiguille, brille, s'obtient par les touches ~YI~
***** Les sons finaux (à compléter)

- la touche ~£~ (L barré) désigne les consonnes de fin de syllabe
  ~Leu~ et ~Reu~ comme dans parmi et libéral ~PA£/MI~ ~LI/P*E/RA£~

- la touche ~$~ désigne les consonnes fricatives de fin de syllabe et
  regroupe les valeurs potentielles suivante : les sons Seu, Zeu, Feu, Veu

  - le sons finaux INS, INZ, INV, INF comme dans prince,
    quinze... s'écrivent d'une seule manière ~In$~. (~PRIn$~, ~KIn$~).

  - le sons finaux OS, OZ, OV, OF comme dans costale, pause, mauve, étoffe
     s'écrivent ~O$~  (~KO$/TA£~, ~PO$~, ~MO$~, ~E/TO$~).

- le son final IME comme dans prime s'écrira ~InC~ et donnera donc
  ~PRInC~. l'adjonction du ~C~ final à ~In~ en change la nature. Il ne
  désignera plus le son ~In~

*** À propos du dictionnaire français et de Plover
Représenter une langue par ses sons permet aux sténotypistes
professionnels d'atteindre des vitesses de prises dépassant les
230 mots par minute. Cette caractéristique a, toutefois, ses revers
quand il s'agit de la traiter informatiquement.
**** TODO Les ~homophones~  :

- vos = veau
- eau = aux
- ce  = se
- et  = est = ait = aie ...
- à faire = affaire
- abreuver = abreuvés = abreuvez
- ...

Aux homophones s'ajoutent les caractéristiques de la disposition
du clavier français :

- Ville  = F*I£
- Vire   = F*I£
- Vile   = F*I£

- bref   = P*RE$
- braise = P*RE$
- ...

Plusieurs mots s'écrivent en utilisant les mêmes accords. Le
concepteur de la disposition du clavier, Marc Grandjean, a choisi
d'assigner à certaines touches plusieurs valeurs potentielles afin que
la composition de tous les sons soit possible sur 21 touches. Ainsi :

- ~£~ peut désigner les sons ~L~ ou ~R~ finaux (les liquides)
- ~$~ peut désigner les sons ~S~, ~Z~, ~F~ ou ~V~ finaux (les fricatives)
- ~D~ peut désigner les sons ~T~, ~D~, ~P~ ou ~B~ finaux (les occlusives)
- ~C~ peut désigner les sons ~K~ ou ~G~ finaux

**** TODO L'héritage de la contrainte mécanique :
Comme pour nos claviers d'ordinateur, le clavier du sténotype semble
sujet au phénomène de la "[[http://en.wikipedia.org/wiki/Path_dependence][dépendance au sentier]]".

La disposition des claviers de nos ordinateurs est un héritage de la
disposition des machines à écrire dont la production à grande échelle
a commencé à la fin du XIX^{e} siècle.

Aux débuts du XX^{e} siècle, la disposition QWERTY s'impose par sa
fiabilité.

#+BEGIN_EXAMPLE
La configuration des claviers d’ordinateurs en QWERTY a été copiée sur
le modèle des claviers des machines à écrire, elle-même créée pour
répondre aux contraintes mécaniques de la première machine à écrire de
Sholes. Les touches correspondant aux paires de lettres les plus
usitées dans la langue anglaise sont réparties de manière à éloigner
le plus possible les marteaux qui lui correspondent, ce qui limite les
risques de blocage des tiges. En raison des usages établis, le choix a
été fait de dupliquer le clavier de la machine à écrire dans
l’informatique.

Source: fr.wikipedia.org/wiki/QWERTY
#+END_EXAMPLE

Bien que des dispositions plus ergonomiques aient été mises au point,
DVORAK aux État-Unis, BEPO en France, la disposition QWERTY et son
héritière française AZERTY sont restés endémiques des bureaux.

En quoi la disposition Grandjean serait-elle concernée par la
dépendance au sentier ?

La disposition Grandjean est restée inchangée depuis sa mise au point
en 1923. À l'époque, et comme pour les machines à écrire, les
impératifs mécaniques ont grandement conditionné la disposition du
clavier et, fatalement, la méthode sténotypique qui en a découlé.

#+BEGIN_EXAMPLE
	|                     |		traduction :
	|         L   A       |-------> La
	|    T *        I  $  |-------> dis
	|  P        O         |-------> po
	|S     *        I    C|-------> sition
	| K    *R     A   ᴎ   |-------> grand
	|          Y  A   ᴎ   |-------> jean
	| K M F R L  E U £ $ C|-------> (*)
	|            E        |-------> est
	|       R    E     $  |-------> res
	|    T       E        |-------> tée
	|               I ᴎ   |-------> in
	|SK           A   ᴎ   |------->	chan
	|          Y E        |-------> gée
	|    T *              |-------> de
	|  P           UI     |-------> puis
	|S            A       |-------> sa
	|   M           I  $  |-------> mise
	|           O         |-------> au
	|  P        O   I ᴎ   |-------> point
	|             A   ᴎ   |-------> en
	|   M           I£    |-------> mille
	|        N   E U   $  |-------> neuf
	|S            A   ᴎ   |-------> cents
	|     F*        I ᴎ D |-------> vingt
	|    T  R   O   I     |-------> trois
	|  P   *             C|------->	.
	|                     |

Figure représentant le placement physique des lettres sur le ruban en
papier d'une machine mécanique et la traduction correspondante de
chaque accord (ou frappe). [17 mots, 102 caractères en 25 frappes]

(*) Un "souligné" (convention sténotypique pour indiquer les noms
propres et mots spéciaux)
#+END_EXAMPLE

La réminiscence mécanique la plus patente dans la sténotypie moderne
est l'ordre et la non permutabilité des touches.

Ainsi le mot "psaume" devra s'écrire en deux frappes ~P/SOnC~ car si
l'on observe la disposition du clavier, la touche ~S~ est placé devant
le ~P~.

Jouer ~SPOnC~ donnerait le son ~SPOME~ dans la théorie établie et
pourrait correspondre à "se paume", conjugaison de la forme
pronominale du verbe "paumer" à la 3e personne du singulier.

La caractéristique de la non permutabilité des touches a été remise en
question dans la [[http://fr.wikipedia.org/wiki/V%25C3%25A9lotypie][vélotypie]], un autre procédé de saisie rapide
*orthographique* qui n'atteint certes pas les performances de la
sténotypie en termes de vitesse mais qui la challenge en termes de
précision et d'intégration technique[1].

Il n'est pas dit qu'une une remise en question des caractéristiques de
la méthode héritées de contingences mécaniques donne lieu à une
amélioration indiscutable de la sténotypie telle qu'elle est pratiquée
et enseignée aujourd'hui.

**** TODO Du dictionnaire français dans Plover
Le lecteur humain peut déduire la correspondance correcte des
sténogrammes, souvent par un mécanisme inconscient de mise en
contexte.

Cette opération mentale, bien plus complexe qu'il n'y paraît, n'est
pas implémentée dans Plover et l'est d'une manière dont l'efficacité
est toute relative dans les logiciels propriétaires et payants de
sténotypie assistée par ordinateur.

Le champs d'études le plus en lien avec la résolution de ce type de
problématiques est le Traitement automatique du langage naturel
(TALN).

*** Les limites de l'approche phonétique
En appliquant une approche purement phonétique pour la construction
d'un dictionnaire sténotypique, on est très vite confronté à la
réalité suivante :

Sur les quelques *125 700* entrées du dictionnaire, *92 000* mots
souffrent d'homophonie. *31 000* entrées du dictionnaire sténotypique
renvoient pour chacune à plusieurs entrée du dictionnaire français.

Un exemple parmi beaucoup d'autres :
#+BEGIN_EXAMPLE
A-LE 	 halez
A-LE 	 hâlés
A-LE 	 halés
A-LE 	 haler
A-LE 	 hâlées
A-LE 	 hâlée
A-LE 	 halée
A-LE 	 hâlé
A-LE 	 halé
A-LE 	 hâlait
A-LE 	 halait
A-LE 	 halaient
A-LE 	 allez
A-LE 	 allés
A-LE 	 allers
A-LE 	 aller
A-LE 	 allées
A-LE 	 allée
A-LE 	 allé
A-LE 	 allait
A-LE 	 allais
A-LE 	 allaient
A-LE 	 allai
#+END_EXAMPLE
23 mots du dictionnaire se transcrivant phonétiquement de la même
manière, avec un seul sténogramme. C'est le cas le plus extrême.

Résoudre cette problématique s'avère donc un préalable incontournable
afin de parvenir à un usage raisonnablement fiable de la sténotypie
avec Plover.

Les écoles américaines de sténotypie tendent à introduire une part
d'orthographe plus ou moins importante dans leurs méthodes.

Ce procédé amène des inconvénients : ajouts de frappes ; dérives vers
des compositions qui n'ont plus aucun trait à la phonétique ;
divergences et cloisonnement des écoles et des méthodes... Rien qui ne
va vers une standardisation de la transcription sténographique.

Voici donc le parti pris pour la construction du dictionnaire français :

- La méthode phonétique de base est le socle du dictionnaire.
- La distinction entre les homophones se fait par le biais de frappes
  supplémentaires suivant une convention détaillée dans un chapitre à venir.

*** La disposition des touches sur le clavier d'ordinateur
**** AZERTY
#+BEGIN_EXAMPLE
 ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ _____
|A  |Z  |E  |R  |T  |Y  |U  |I  |O  |P  |^  |$  |Enter|
|___|___|___|___|___|___|___|___|___|___|___|___|     |
 |Q  |S  |D  |F  |G  |H  |J  |K  |L  |M  |Ù  |*  |  ⏎ |
_|___|___|___|___|___|___|___|___|___|___|___|___|____|
   |W  |X  |C  |V  |B  |N  |,  |;  |:  |!  |⇧         |
___|___|___|___|___|___|___|___|___|___|___|__________|
#+END_EXAMPLE
**** Disposition Grandjean sur un clavier d'ordinateur
#+BEGIN_EXAMPLE
 ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ _____
|S  |P  |T  |*  |N  |   |O  |A  |I  |ᴎ  |D  |   |Enter|
|__a|__z|__e|__r|__t|___|__u|__i|__o|__p|__^|___|     |
 |K  |M  |F  |R  |L  |Y  |E  |U  |£  |$  |C  |   |  ⏎ |
_|__q|__s|__d|__f|__g|__h|__j|__k|__l|__m|__ù|___|____|
   |   |   |   |L  |Y  |Y  |E  |   |   |   |⇧         |
___|___|___|___|__v|__b|__n|___|___|___|___|__________|
#+END_EXAMPLE

**** Clavier sténotypique anglosaxon en usage dans Plover
#+BEGIN_EXAMPLE
 ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ _____
|S  |T  |P  |H  |*  |*  |F  |P  |L  |T  |D  |   |Enter|
|__a|__z|__e|__r|__t|__y|__u|__i|__o|__p|__^|___|     |
 |S  |K  |W  |R  |*  |*  |R  |B  |G  |S  |Z  |   |  ⏎ |
_|__q|__s|__d|__f|__g|__h|__j|__k|__l|__m|__ù|___|____|
   |   |   |A  |O  |   |E  |U  |   |   |   |⇧         |
___|___|___|__c|__v|___|__n|__,|___|___|___|__________|
#+END_EXAMPLE

* Footnotes
[1] Les performances vélotypiques en termes de vitesse avoisinent
les 150 mots/minute, loin derrière la sténotypie à 210 mots
/minute. Toutefois, la vélotypie a réussi son accès au sous-titrage
des programmes audiovisuels en direct.
