#+BEGIN_EXAMPLE
  ___                                           ___
 | S |___                                   ___| D |
 |___| P |___                           ___| ᴎ |___|
 | K |___| T |___                   ___| I |___| C |
 |___| M |___| * |___     _     ___| A |___| $ |___|
     |___| F |___| N |   / \   | O |___| Ł |___|
         |___| R |___|  /   \  |___| U |___|
             |___| L | /  Y  \ | E |___|
                 |___||       ||___|
                       \_____/
#+END_EXAMPLE

#+BEGIN_EXAMPLE
 _____ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ _____
|TAB  | S | P | T | * | L |   | O | A | I | ᴎ | D |   |Enter|
|_____|___|___|___|___|___|___|___|___|___|___|___|___|     |
|MAJ   |K  |M  |F  |R  |L  |Y  |E  |U  |Ł  |$  |C  |   |  ⏎ |
|______|___|___|___|___|___|___|___|___|___|___|___|___|____|
| ⇧  |   |   |   |   |  L|  Y|  E|   |   |   |   |⇧         |
|____|___|___|___|___|___|___|___|___|___|___|___|__________|
#+END_EXAMPLE

*** Si vous voulez essayer Plover avec ce clavier :
https://github.com/azizyemloul/plover-france

*** Construction d'un dictionnaire français pour Plover
La base de données lexicales libre [[http://www.lexique.org/][Lexique]] est le fondement de la
construction d'un dictionnaire sténotypique au format JSON requis par
le projet [[http://plover.stenoknight.com/][Plover]].

Le fichier original contenant cette base de données est
~Lexique380.txt~.

Les colonnes qui nous intéressent dans cette large base, qui se
présente sous forme d'un tableau texte géant, sont ~1_ortho~ et
~23_syll~.

J'ai dû m'y reprendre à plusieurs reprises sur une période de
plusieurs mois pour aboutir au fichier ~dict-base.txt~.[fn:1]

Le fichier ~dict-base-uniq.txt~ est une version expurgée de doublons.

Le fichier ~france_french_words.txt~ servant à la vérification
orthographique[fn:2] provient également des travaux des équipes
[[http://www.lexique.org/listes/liste_mots.txt][Lexique]].

Le fichier ~fr.aff~ fait partie de la distribution [[http://hunspell.sourceforge.net/][Hunspell]], un
analyseur orthographique et morphologique prenant en charge la langue
française. Il sert de base à la définition des règles d'affixation
contenus dans ~orthography.py~.
*** À propos de la sténotypie
La sténotypie est une méthode de saisie qui tend à représenter le
parole dans une langue donnée par les sons que celle-ci est en mesure
de produire.

Elle tire son héritage de la sténographie en lui apportant une
importante amélioration : tracés à la main, les caractères
sténographiques sont propres au sténographe qui les a dessinés et
peuvent difficilement être interprétés par un autre lecteur.

La sténotype - ainsi est appelée la machine de sténotypie - apporte
donc le moyen de produire des signes sténographiques "types"
reconnaissables par n'importe quel lecteur instruit des règles de
base.

Le clavier de la sténotype Grandjean en usage en France a été conçu
par l'ingénieur [[http://fr.wikipedia.org/wiki/Marc_Grandjean][Marc Grandjean]]. La première sténotype Grandjean a été
commercialisée en 1923.

#+BEGIN_EXAMPLE
  ___                                           ___
 | S |___                                   ___| D |
 |___| P |___                           ___| ᴎ |___|
 | K |___| T |___                   ___| I |___| C |
 |___| M |___| * |___     _     ___| A |___| $ |___|
     |___| F |___| N |   / \   | O |___| Ł |___|
         |___| R |___|  /   \  |___| U |___|
             |___| L | /  Y  \ | E |___|
                 |___||       ||___|
                       \_____/
#+END_EXAMPLE

Les cinq doigts de chaque main se positionnement d'un côté et de
l'autre de la touche centrale ~Y~, sur la rangée du bas. C'est ce
qu'on appelle la ~position de départ~ ou de repos.

La touche du milieu ~Y~ n'est actionnée que par le pouce de la main
gauche qui reviendra immédiatement après sur sa touche de repos,
c'est-à-dire le ~L~.

Une prise sténotypique consiste à appuyer sur plusieurs touches à la
fois et produit un accord représentant une unité de son.


- La partie gauche du clavier, actionnée par les doigts de la main
  gauche, représente les ~sons de initiaux~ et est constituée de
  consonnes seulement ;
- Les voyelles (~OEAUI~) sont placées sur la partie droite du clavier,
  actionnée par les doigts de la main droite ;
- Les signes parfois étranges (~Łᴎ$DC~) à l'extrême droite
  représentent les ~sons finaux~.

Un exemple pour bien comprendre :

- Affaire s'écrira A/FEŁ
- Rapide  s'écrira RA/PID

Une explication. Pour écrire A/FEŁ :

1) On appuie avec l'index de la main droite sur ~A~
2) On relâche et on fait revenir son index à sa position de départ, au dessus de la touche ~U~.

Ceci pour la premier accord qui n'aura au final été constitué que d'une seule note.
Continuons sur le deuxième accord qui compose ce mot :


3) On appuie de son majeur de la main gauche sur la touche ~F~ ;
4) Tout en maintenant ~F~ appuyé, on enfonce du pouce de la main
   droite la touche ~E~
5) Avec le majeur de la main droite, on enfonce la touche ~Ł~.
6) Les trois touches sont toutes appuyées comme pour un accord de
   piano.
7) On relâche les touches toutes à la fois
8) On fait revenir ses doigts à leurs positions de repos, sur la rangée
   du bas. Il se trouve que pour cette exemple ils y sont déjà.

Ce n'est pas le cas dans le deuxième exemple, le mot ~RA/PID~ :

1) Index gauche sur la touche ~R~
2) Index droit sur ~A~
3) On relâche les deux doigts et on ramène l'index droit à se position
   de départ au dessus de ~U~.
4) Le signe ~/~ indique la fin d'un accord.

Le deuxième accord ~PID~ vous l'aurez compris se joue avec :

5) L'annulaire de la main gauche sur ~P~
6) Le majeur de la main droite sur ~I~
7) L'auriculaire droit sur ~D~
8) On relâche l'accord
9) On fait revenir tout ce petit monde à sa place, respectivement ~M~,
   ~Ł~ et ~C~.

Il est important de veillez respecter ce mouvement de va et vient vers
la position de départ après chaque frappe.

Il s'agit d'une stratégie d'apprentissage, l'objectif étant de créer
des réactions réflexes sur le modèle d'un coureur aux 100 mètres :
celui-ci doit s'entraîner à réduire son temps de réaction entre le top
de départ et sa première impulsion musculaire de propulsion.

Pour un sténotypiste ce temps de réaction est aussi important et pour
ce faire il faut, comme pour un coureur aux 100 mètres, se tenir sur
des starting-blocks matérialisés par la station de départ, les 10
doigts placés sur la première rangée.

On a composé deux mots, de 7 et 6 lettres respectivement, avec 2
accords pour chacun, c'est-à-dire 2 mouvements. C'est cette différence
qui explique la rapidité qu'acquièrent les sténotypistes professionnels.
*** À propos du dictionnaire français pour Plover
Représenter une langue par ses sons permet aux sténotypistes
professionnels d'atteindre des vitesses de prises dépassant les
230 mots par minute. Cette caractéristique a, toutefois, ses revers
quand il s'agit de la traiter informatiquement.
**** TODO Les ~homophones~  :

- vos = veau
- eau = aux
- ce  = se
- et  = est = ait = aie ...
- à faire = affaire
- abreuver = abreuvés = abreuvez
- ...

Aux homophones s'ajoutent les caractéristiques de la disposition
du clavier français :

- Ville  = F*IŁ
- Vire   = F*IŁ
- Vile   = F*IŁ

- bref   = P*RE$
- braise = P*RE$
- ...

Plusieurs mots s'écrivent en utilisant les mêmes accords. Le
concepteur de la disposition du clavier, Marc Grandjean, a choisi
d'assigner à certaines touches plusieurs valeurs potentielles afin que
la composition de tous les sons soit possible sur 21 touches. Ainsi :

- ~Ł~ peut désigner les sons ~L~ ou ~R~ finaux
- ~$~ peut désigner les sons ~S~, ~Z~, ~F~ ou ~V~ finaux ( consonnes fricatives )
- ~D~ peut désigner les sons ~T~, ~D~, ~P~ ou ~B~ finaux ( consonnes occlusives )
- ~C~ peut désigner les sons ~K~ ou ~G~ finaux

**** TODO L'héritage de la contrainte mécanique :
Comme pour nos claviers d'ordinateur, le clavier du sténotype semble
sujet au phénomène de la "[[http://en.wikipedia.org/wiki/Path_dependence][dépendance au sentier]]".

La disposition des claviers de nos ordinateurs est un héritage de la
disposition des machines à écrire dont la production à grande échelle
a commencé à la fin du XIX^{e} siècle.

Aux débuts du XX^{e} siècle, la disposition QWERTY s'impose par sa
fiabilité.

#+BEGIN_EXAMPLE
La configuration des claviers d’ordinateurs en QWERTY a été copiée sur
le modèle des claviers des machines à écrire, elle-même créée pour
répondre aux contraintes mécaniques de la première machine à écrire de
Sholes. Les touches correspondant aux paires de lettres les plus
usitées dans la langue anglaise sont réparties de manière à éloigner
le plus possible les marteaux qui lui correspondent, ce qui limite les
risques de blocage des tiges. En raison des usages établis, le choix a
été fait de dupliquer le clavier de la machine à écrire dans
l’informatique.

Source: fr.wikipedia.org/wiki/QWERTY
#+END_EXAMPLE

Bien que des dispositions plus ergonomiques aient été mises au point,
DVORAK aux État-Unis, BEPO en France, la disposition QWERTY et son
héritière française AZERTY sont restés endémiques des bureaux.

En quoi la disposition Grandjean serait-elle concernée par la
dépendance au sentier ?

La disposition Grandjean est restée inchangée depuis sa mise au point
en 1923. À l'époque, et comme pour les machines à écrire, les
impératifs mécaniques ont grandement conditionné la disposition du
clavier et, fatalement, la méthode sténotypique qui en a découlé.

#+BEGIN_EXAMPLE
	|                     |		traduction :
	|         L   A       |	->	La
	|    T *        I  $  |	->	dis
	|  P        O         |	->	po
	|S     *        I    C|	->	sition
	| K    *R     A   n   |	->	grand
	|          Y  A   n   |	->	jean
	|             E       |	->	est
	|       R    E     $  |	->	res
	|    T       E        |	->	tée
	|               I n   |	->	in
	|SK           A   n   |	->	chan
	|          Y E        |		gée
	|    T *              |		de
	|  P           UI     |		puis
	|S            A       |		sa
	|   M           I  $  |		mise
	|           O         |		au
	|  P        O   I n   |		point
	|             A   n   |		en
	|   M           Il    |		mille
	|        N   E U   $  |		neuf
	|S            A   n   |		cent
	|     F*        I n D |		vingt
	|    T  R   O   I     |		trois
	|                     |
#+END_EXAMPLE
#+CAPTION: Figure représentant le placement physique des lettres sur un ruban d'une machine mécanique et la traduction correspondante

La réminiscence mécanique la plus patente dans la sténotypie moderne
est l'ordre et la non permutabilité des touches.

Ainsi le mot "psaume" devra s'écrire en deux frappes ~P/SOnC~ car si
l'on observe la disposition du clavier, la touche ~S~ est placé devant
le ~P~. Jouer ~SPOnC~ donnerait le son ~SPOME~ dans la théorie établie.

Cette caractéristique a été remise en question par la [[http://fr.wikipedia.org/wiki/V%25C3%25A9lotypie][vélotypie]], une
autre méthode de saisie rapide *orthographique* qui n'atteint certes pas
les performances de la sténotypie en termes de vitesse.

Il n'est pas dit qu'une réflexion autour de la disposition des lettres
ou qu'une une remise en question des caractéristiques de la méthode
héritées de l'influence de contingences mécaniques n'ayant plus court
donnent lieu à une amélioration indiscutable de la sténotypie telle
qu'elle continue à être pratiquée ou enseignée.

**** TODO L'usage et la perspective :
Le lecteur humain peut déduire la correspondance correcte, souvent par
un mécanisme inconscient de mise en contexte.

Cette opération mentale, plus complexe qu'il n'y paraît, n'est pas
implémentée dans Plover et l'est d'une manière dont l'efficacité est
toute relative dans les logiciels propriétaires et payants de
sténotypie assistée par ordinateur.

Le champs d'études le plus en lien avec la résolution de ce type de
problématiques est le Traitement automatique du langage naturel
(TALN).[fn:3]

*** Les limites de l'approche phonétique
En appliquant une approche purement phonétique pour la construction
d'un dictionnaire sténotypique, on est très vite confronté à la
réalité suivante :

Sur les quelques *125 700* entrées du dictionnaire, *92 000* mots
souffrent d'homophonie. *31 000* entrées du dictionnaire sténotypique
renvoient pour chacune à plusieurs entrée du dictionnaire français.

Un exemple parmi beaucoup d'autres :

#+BEGIN_EXAMPLE
A-LE 	 halez
A-LE 	 hâlés
A-LE 	 halés
A-LE 	 haler
A-LE 	 hâlées
A-LE 	 hâlée
A-LE 	 halée
A-LE 	 hâlé
A-LE 	 halé
A-LE 	 hâlait
A-LE 	 halait
A-LE 	 halaient
A-LE 	 allez
A-LE 	 allés
A-LE 	 allers
A-LE 	 aller
A-LE 	 allées
A-LE 	 allée
A-LE 	 allé
A-LE 	 allait
A-LE 	 allais
A-LE 	 allaient
A-LE 	 allai
#+END_EXAMPLE
23 mots du dictionnaire se transcrivant phonétiquement de la même
manière, avec un seul sténogramme. C'est le cas le plus extrême.

Résoudre cette problématique s'avère donc un préalable incontournable
afin de parvenir à un usage raisonnablement fiable de la sténotypie
avec Plover.

Les écoles américaines de sténotypie tendent à introduire une part
d'orthographe plus ou moins importante dans leurs méthodes.

Ce procédé amène des inconvénients : ajouts de frappes ; dérives vers
des compositions qui n'ont plus aucun trait à la phonétique ;
divergences et cloisonnement des écoles et des méthodes... Rien qui ne
va vers une standardisation de la transcription sténographique.



Voici donc le parti pris pour la construction du dictionnaire français :

- La méthode phonétique de base est le socle du dictionnaire.
- La distinction entre les homophones se fait par le biais de frappes
  supplémentaires suivant une convention détaillée au titre suivant.

*** La disposition des touches sur le clavier d'ordinateur
**** AZERTY
#+BEGIN_EXAMPLE
 ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ _____
|A  |Z  |E  |R  |T  |Y  |U  |I  |O  |P  |^  |$  |Enter|
|___|___|___|___|___|___|___|___|___|___|___|___|     |
 |Q  |S  |D  |F  |G  |H  |J  |K  |L  |M  |Ù  |*  |  ⏎ |
_|___|___|___|___|___|___|___|___|___|___|___|___|____|
   |W  |X  |C  |V  |B  |N  |,  |;  |:  |!  |⇧         |
___|___|___|___|___|___|___|___|___|___|___|__________|
#+END_EXAMPLE
**** Disposition Grandjean sur un clavier d'ordinateur
#+BEGIN_EXAMPLE
 ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ _____
|S  |P  |T  |*  |N  |   |O  |A  |I  |ᴎ  |D  |   |Enter|
|__a|__z|__e|__r|__t|___|__u|__i|__o|__p|__^|___|     |
 |K  |M  |F  |R  |L  |Y  |E  |U  |Ł  |$  |C  |   |  ⏎ |
_|__q|__s|__d|__f|__g|__h|__j|__k|__l|__m|__ù|___|____|
   |   |   |   |L  |Y  |E  |   |   |   |   |⇧         |
___|___|___|___|__v|__b|__n|___|___|___|___|__________|
#+END_EXAMPLE

**** Clavier sténotypique anglosaxon en usage dans Plover
#+BEGIN_EXAMPLE
 ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ _____
|S  |T  |P  |H  |*  |*  |F  |P  |L  |T  |D  |   |Enter|
|__a|__z|__e|__r|__t|__y|__u|__i|__o|__p|__^|___|     |
 |S  |K  |W  |R  |*  |*  |R  |B  |G  |S  |Z  |   |  ⏎ |
_|__q|__s|__d|__f|__g|__h|__j|__k|__l|__m|__ù|___|____|
   |   |   |A  |O  |   |E  |U  |   |   |   |⇧         |
___|___|___|__c|__v|___|__n|__,|___|___|___|__________|
#+END_EXAMPLE
* Renvois
[fn:1] Le fichier est une correspondance orthographe<-->sténogramme
selon la disposition de clavier sténotypique français. Se rapporter à
[[https://github.com/azizyemloul/plover-france][Plover-france]] pour plus d'informations.

[fn:2] https://groups.google.com/forum/#!topic/ploversteno/pO6WVs9MzK8

[fn:3] Ceci est une piste de travail que je souhaiterais éprouver
notamment dans le cadre de ce projet Plover mais dont la technicité
requière une implication exceptionnelle.

#  LocalWords:  Plover sténotypique texte JSON LocalWords Grandjean
#  LocalWords:  Hunspell orthography.py
